---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privileged-containers
  annotations:
    policies.kyverno.io/title: Disallow Privileged Containers
    policies.kyverno.io/category: Pod Security Standards (Baseline)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/description: >-
      Privileged mode disables most security mechanisms and must not be allowed. This policy
      ensures Pods do not call for privileged mode.      
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: privileged-containers
      match:
        any:
        - resources:
            kinds:
              - Pod
            namespaces:
              - "user*"
      validate:
        message: >-
          Privileged mode is disallowed. The fields spec.containers[*].securityContext.privileged,
          spec.initContainers[*].securityContext.privileged, and spec.ephemeralContainers[*].securityContext.privileged must be unset or set to `false`.          
        foreach:
        - list: "request.object.spec.[ephemeralContainers, initContainers, containers][]"
          deny:
            conditions:
              all:
              - key: "{{ element.securityContext.privileged || `false` }}"
                operator: Equals
                value: true
              - key: "{{ element.image }}"
                operator: NotEquals
                value: "docker.io/docker:*dind-rootless*"
              - key: "{{ element.image }}"
                operator: NotEquals
                value: "docker:*dind-rootless*"
